nbip_server/nbip/urls.py
from django.conf.urls import patterns, url

from nbip import views, bot_views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^highscore/$', views.highscore, name='highscore'),

    # human interaction
    url(r'^submit/$', views.submit, name='submit'),
    url(r'^explain/$', views.explain, name='explain'),
    url(r'^guess/$', views.new_guess, name='new_guess'),
    url(r'^guess/(\d+)/$', views.guess, name='guess'),
    url(r'^view_guess/(\d+)/$', views.view_guess, name='view_guess'),
    url(r'^bot/(\d+)/$', views.view_bot, name='view_bot'),

    # bot management
    url(r'^new_bot/$', views.new_bot, name='new_bot'),

    # bot interface
    url(r'^bot/get/$', bot_views.get, name='bot_get'),
    url(r'^bot/put/$', bot_views.put, name='bot_pu'),

    # Raw data
    url(r'^highscore_data/$', views.highscore_data, name='highscore_data'),
)

nbip_server/nbip_server/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView, TemplateView
from registration.backends.simple.views import RegistrationView

admin.autodiscover()

urlpatterns = patterns('',
    # http://www.voidynullness.net/blog/2014/01/15/raiders-of-the-lost-django-registration-templates/
    url(r'^accounts/login/$',
                    auth_views.login,
                    {'template_name': 'nbip/login.html'},
                    name='auth_login'),
    url(r'^accounts/logout/$',
                    auth_views.logout,
                    {'template_name': 'nbip/logout.html'},
                    name='auth_logout'),
    url(r'^accounts/password/change/$',
                    auth_views.password_change,
                    {'template_name': 'nbip/password_change_form.html'},
                    name='password_change'),
    url(r'^accounts/password/change/done/$',
                    auth_views.password_change_done,
                    {'template_name': 'nbip/password_change_done.html'},
                    name='password_change_done'),

    url(r'^accounts/password/reset/$',
                    auth_views.password_reset,
                    name='password_reset'),
    url(r'^accounts/password/reset/done/$',
                    auth_views.password_reset_done,
                    name='password_reset_done'),
    url(r'^accounts/password/reset/complete/$',
                    auth_views.password_reset_complete,
                    name='password_reset_complete'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                    auth_views.password_reset_confirm,
                    name='password_reset_confirm'),

    # url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/register/$',
                    RegistrationView.as_view(template_name='nbip/registration_form.html'),
                    name='registration_register'),
    url(r'^accounts/register/closed/$',
                    TemplateView.as_view(template_name='nbip/registration_closed.html'),
                    name='registration_disallowed'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('nbip.urls')),
)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

nbip_server/nbip/models.py
# coding=utf-8

import random
import re

from django.db import models, transaction
from django.db.models import Count, Q
from django.contrib.auth.models import User
from django.conf import settings

from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

import django.utils.http

# Enumeration type
class Guess(int):
    def __init__(self, value):
        if value is None:
            self=None
        else:
            value=int(value)
            assert 0 <= value < 3, "value %s out of range" % value
            self=value

    # Breaks the admin form
    #def __unicode__(self):
    #    return {
    #        0: 'Richtig',
    #        1: 'Mensch',
    #        2: 'Computer',
    #    }[int(self)]



# Constants
CORRECT = Guess(0)
HUMAN = Guess(1)
COMPUTER = Guess(2)

# Custom fields
class GuessField(models.PositiveSmallIntegerField):
    description = "Choice: Correct, Human or Bot"

    __metaclass__ = models.SubfieldBase

    def __init__(self, *args, **kwargs):
        kwargs['choices'] = [
             (CORRECT, 'Richtig')
           , (HUMAN, 'Mensch')
           , (COMPUTER, 'Computer')
           ]
        kwargs['null'] = True
        super(GuessField, self).__init__(*args, **kwargs)

    def to_python(self, value):
        if value is None:
            return None

        if isinstance(value, Guess):
            return value

        return Guess(value)

    def formfield(self, **kwargs):
        defaults = {'coerce': lambda x: Guess(x)}
        defaults.update(kwargs)
        return super(GuessField, self).formfield(**defaults)

from south.modelsinspector import add_introspection_rules
add_introspection_rules([], ["^nbip\.models\.GuessField"])

# Exceptions

class NotEnoughWordsException(Exception):
    pass

class NotEnoughExplanationsException(Exception):

    def missing_human_explanations(self):
        return self.args[0]

    def missing_bot_explanations(self):
        return self.args[1]

# Models

class Bot(models.Model):
    class Meta:
        verbose_name = "Bot"
        verbose_name_plural = u"Bots"

    owner = models.ForeignKey(User, verbose_name="Benutzer", related_name = "bots")
    name = models.CharField(max_length=200, verbose_name="Bot-Name")
    apikey = models.CharField(max_length=100, unique=True, verbose_name="API-Key")
    explaining = models.ForeignKey('Word', verbose_name="Erklärt gerade", null=True)

    def __unicode__(self):
        return "%s by %s" % (self.name, self.owner)

    def word_to_explain(self):
        if not self.explaining:
            word = Word.random_for_bot(bot = self)
            self.explaining = word
            self.save()
        return self.explaining

    @transaction.atomic
    def explain_word(self, expl):
        expl = Explanation(
            word = self.explaining,
            explanation = expl,
            bot = self);
        expl.save()
        self.explaining = None
        self.save()


class Word(models.Model):
    class Meta:
        verbose_name = "Wort"
        verbose_name_plural = u"Wörter"

    lemma = models.CharField(max_length=200)
    correct_explanation = models.CharField(max_length=1000,
            verbose_name = "Korrekte Erklärung",
            help_text= u"<i>Wort</i> ist ein/eine <i>Erklärung</i>")
    reference = models.URLField(blank=True,
            verbose_name = "Referenz",
            help_text = u"URL zu Wikipedia o.ä.")

    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, verbose_name="Autor", related_name="submitted_words")

    n_human_explanations = models.PositiveIntegerField(
            verbose_name = "Anzahl menschliche Erklärungen",
            default = 0)
    n_bot_explanations = models.PositiveIntegerField(
            verbose_name = "Anzahl Computer-Erklärungen",
            default = 0)

    # query components (Q objects)
    @classmethod
    def q_owner(cls, player):
        return Q(author__exact = player.id)

    @classmethod
    def q_explained(cls, player):
        explained = Explanation.objects.filter(author__exact = player).values("word")
        return Q(id__in = explained)

    @classmethod
    def q_bot_explained(cls, bot):
        explained = Explanation.objects.filter(bot__exact = bot).values("word")
        return Q(id__in = explained)

    @classmethod
    def q_guessed(cls, player):
        guessed = GameRound.objects.filter(player__exact = player).values("word")
        return Q(id__in = guessed)

    @classmethod
    def q_unseen(cls, player):
        return Q(~cls.q_owner(player) & ~cls.q_explained(player) & ~cls.q_guessed(player))

    @classmethod
    def q_answer_unseen(cls, player):
        return Q(~cls.q_owner(player) & ~cls.q_guessed(player))

    @classmethod
    def q_possibly_complete(cls):
        return Q(n_human_explanations__gte = settings.HUMAN_EXPLANATIONS) & \
               Q(n_bot_explanations__gte   = settings.BOT_EXPLANATIONS)

    @classmethod
    def random(cls, player):
        ''' Fetch a random to be explained '''
        words = cls.objects \
            .filter(cls.q_unseen(player))

        if len(words) < 1:
            raise NotEnoughWordsException()

        needy_words = words \
            .filter(n_human_explanations__lte = settings.HUMAN_EXPLANATIONS) \
            .order_by('-n_human_explanations','-n_bot_explanations')

        # If there are words with insufficient answers, return the one that is closest
        # to having sufficient
        if needy_words:
            return needy_words.first()

        # Otherwise return a random word
        return random.choice(words)

    @classmethod
    def random_for_bot(cls, bot):
        ''' Fetch a random to be explained by a bot '''
        words = cls.objects \
            .exclude(cls.q_bot_explained(bot))

        if len(words) < 1:
            raise NotEnoughWordsException()

        needy_words = words \
            .filter(n_bot_explanations__lte = settings.BOT_EXPLANATIONS) \
            .order_by('-n_bot_explanations','-n_human_explanations')

        # If there are words with insufficient answers, return the one that is closest
        # to having sufficient
        if needy_words:
            return needy_words.first()

        # Otherwise return a random word
        return random.choice(words)

    def usable_for(self, player):
        usable_human_explanations = \
            self.explanation_set \
                .filter(author__isnull = False) \
                .exclude(author = player) \
                .count()

        usable_bot_explanations = \
            self.explanation_set \
                .filter(bot__isnull = False) \
                .exclude(bot__in = player.bots.all()) \
                .count()

        return (usable_human_explanations >= settings.HUMAN_EXPLANATIONS and
                 usable_bot_explanations >= settings.BOT_EXPLANATIONS)


    @classmethod
    # similar to random, but only consider words with enough explanations
    def random_explained(cls, player):
        candidates = cls.objects \
            .filter(cls.q_answer_unseen(player))

        # This could possibly be rewritten with SQL, but seems to be tricky
        words = filter(lambda w: w.usable_for(player),
                candidates.filter(cls.q_possibly_complete()))

        # fetches everything; be smarter if required
        if not words:
            best = candidates \
                .order_by('-n_human_explanations', '-n_bot_explanations') \
                .first()
            if best:
                # This is only an approximation, if the current user has explained that
                # word already.
                raise NotEnoughExplanationsException(
                        settings.HUMAN_EXPLANATIONS - best.n_human_explanations,
                        settings.BOT_EXPLANATIONS   - best.n_bot_explanations
                    )
            else:
                raise NotEnoughWordsException()
        return random.choice(words)

    def update_cached_fields(self):
        self.n_human_explanations = \
            Explanation.objects.filter(author__isnull = False, word__exact = self.id).count()
        self.n_bot_explanations = \
            Explanation.objects.filter(bot__isnull = False, word__exact = self.id).count()
        self.save()

    def clean_an_explanation(self, e):
        r = r"(eine?)? ?(" + re.escape(self.lemma) + \
            r")? ?(ist)? ?(eine?) ?"
        m = re.match(r, e, re.IGNORECASE)
        if m:
            return e[m.end(0):]
        else:
            return e

    def clean_explanation(self):
        return self.clean_an_explanation(self.correct_explanation)

    def link(self):
        if self.reference:
            return self.reference
        else:
            return "https://duckduckgo.com/?q=%s" % django.utils.http.urlquote(self.lemma)

    def __unicode__(self):
        return self.lemma

class Explanation(models.Model):
    class Meta:
        verbose_name = u"Erklärung"
        verbose_name_plural = u"Erklärungen"

    word = models.ForeignKey(Word, verbose_name="Wort")
    explanation = models.CharField(max_length=1000,
            verbose_name= u"Erklärung",
            help_text= u"<i>Wort</i> ist ein/eine <i>Erklärung</i>")

    # exactly one of these should be not null
    author = models.ForeignKey(User, verbose_name="Autor", blank=True, null=True, related_name="submitted_explanations")
    bot = models.ForeignKey(Bot, verbose_name="Bot", blank=True, null=True, related_name="submitted_explanations")

    def clean(self):
        if self.author is None and self.bot is None:
            raise ValidationError('Autor oder Bot müssen gesetzt sein.')
        if self.author is not None and self.bot is not None:
            raise ValidationError('Autor und Bot dürfen nicht beide gesetzt sein.')

    def clean_explanation(self):
        return self.word.clean_an_explanation(self.explanation)

    def type(self):
        '''HUMAN or COMPUTER'''

nbip_server/nbip/templates/nbip/base.html
{% load staticfiles %}
{% load current from navigation %}
<!DOCTYPE html>
<html lang="de">
<head>
<title>No bot is perfect – {% block title %}{% endblock %}</title>
<style type="text/css">
/*
 Have the icon have no influence on the navigation height.
 http://stackoverflow.com/a/11818212/946226 
 */
.navbar .navbar-brand.logo {
    max-height: 1px;
    overflow: visible;
    padding-top: 0;
    padding-bottom: 0;
}

/* Based on http://matthewjamestaylor.com/blog/keeping-footers-at-the-bottom-of-the-page */
html,
body {
   margin:0;
   padding:0;
   height:100%;
}
#wrap {
   min-height:100%;
   position:relative;
}
#footer-space {
   padding-bottom:50px;   /* Height of the footer */
}
#footer {
   position:absolute;
   bottom:0;
   width:100%;
   height:50px;   /* Height of the footer */
   background-color: rgb(238,238,238);
}
#footer .navbar {
   margin: 0px;
   border: 0px;
}
#footer a {
   color: inherit;
}



{% block page-css %}{% endblock %}

</style>

<!-- Bootstrap -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.1.1/cosmo/bootstrap.min.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
{% block page-header %}{% endblock %}

<script type="text/javascript">
{% block page-js %}{% endblock %}
</script>

</head>

<body>
<div id="wrap">

<nav class="navbar navbar-default navbar-static-top" role="navigation">
<div class="container">

<div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

<a class="navbar-brand logo" href="{% url 'index' %}">
  <img src="{% static "Maria-50.png" %}" alt="Logo"/>
</a>
<a class="navbar-brand" href="{% url 'index' %}">
  No bot is perfect
</a>
</div>

<div class="collapse navbar-collapse" id="navbar-collapse">

<ul class="nav navbar-nav">
<li class="{% current 'submit' return_value='active' %}"><a href="{% url 'submit' %}">Neues Wort</a></li>
<li class="{% current 'explain' return_value='active' %}"><a href="{% url 'explain' %}">Erklären</a></li>
<li class="{% current 'new_guess' return_value='active' %} {% current 'guess' return_value='active' %}"><a href="{% url 'new_guess' %}">Raten</a></li>
<li class="{% current 'highscore' return_value='active' %}"><a href="{% url 'highscore' %}">Highscores</a></li>
</ul>
 
</div>
</div>
</nav>


{% if messages %}
 <div class="container">
  {% for message in messages %}
   <div class="alert alert-{{ message.tags }}">
    <button type="button" class="close" aria-hidden="true" data-dismiss="alert">&times;</button>
    {{ message }}
   </div>
  {% endfor %}
 </div>
{% endif %}

{% block content %}{% endblock %}

<div id="footer-space"/>

<div id="footer">
 <div class="navbar">
   <div class="container">
    <p class="text-muted navbar-text">
     <a href="https://github.com/entropia/no-bot-is-perfect">Source</a>
    </p>
    <p class="text-muted navbar-text">
     <a href="https://github.com/entropia/no-bot-is-perfect/issues">Issues</a>
    </p>

   {% if user.is_authenticated %}
    <div class="navbar-right">
     <p class="navbar-text">
      Hallo <a href="{% url 'stats' %}" class="navbar-link">{{user}}</a>!
     </p>
    </div>
   {% else %}
    <a href="{% url 'registration_register' %}" class="navbar-right btn navbar-btn">Registrieren</a>
    <a href="{% url 'auth_login' %}" class="navbar-right btn navbar-btn">Einloggen</a>
   {% endif %}
  </div>
 </div>
</div>

</div> <!-- wrap -->

</body>
</html>

nbip_server/nbip/templates/nbip/bot.html
{% extends "nbip/base.html" %}

{% block page-css %}
ul.contributions {
	max-height:12em;
	overflow-y:auto;
}

h4 {
	white-space:nowrap;
}

{% endblock %}

{% block title %}{{ bot.name }}{% endblock %}

{% block content %}

<div class="container">
 <div class="row">
  <div class="col-sm-6 col-md-6">
   <h4>
    Erklärungen von {{bot.name}}
   </h4>
   {% if expls  %}
    <ul class="list-group contributions">
     {% for e in expls %}
      <li class="list-group-item">
       Ein/eine <strong>{{e.word}}</strong> ist ein/eine <strong>{{e.explanation}}</strong>.
      </li>
     {% endfor %}
    </ul>
  {% else %}
   <p>
    {{bot.name}} hat noch keine Erklärungen eingericht. Warum denn nicht?
   </p>
  {% endif %}
  </div>
 </div>
</div>

<div class="container">
 <h4>API-Key</h4>
 <code>{{ bot.apikey }}</code>
</div>

{% endblock %}

nbip_server/nbip/templates/nbip/explain.html
{% extends "nbip/base.html" %}
{% load bootstrap %}

{% block title %}Neues Wort einreichen{% endblock %}

{% block content %}
<div class="container">
<form class="form-horizontal" role="form" method="POST">
{% csrf_token %}

{% for hidden in form.hidden_fields %}
    {{ hidden }}
{% endfor %}

<div class="form-group">
  <span class="control-label col-sm-4 col-lg-4 ">
   Ein/eine <strong>{{word.lemma}}</strong> ist ein/eine
  </span>
  <div class="col-sm-4 col-lg-4 ">
    <input class="form-control" id="id_explanation" name="explanation" type="text" placeholder="&lt;Adjektiv&gt; &lt;Substantiv&gt;"/>
  </div>
 <div class="col-sm-2 col-lg-2">
  <input  class="btn btn-default" type="submit" value="Submit" />
 </div>
</div>
</form>

</div>

{% endblock %}

nbip_server/nbip/templates/nbip/guess.html
{% extends "nbip/base.html" %}
{% load staticfiles %}
{% load countup %}

{% block title %}Was ist richtig?{% endblock %}

{% block page-js %}
// Grey out the submit button if the answers do not make sense
function update_submit () {
	var counts = [0,0,0];
	$(".result-count").each(function (_,input) {
		var n = $(input).attr('name').substr(6);
		counts[n] = $(input).val();
	});

	var actual = [0,0,0];
	$("select").each(function (_,select) {
		var n = $(select).val();
		if (n) {actual[n]++};
	});

	$(":submit").attr("disabled", false);
	$(":submit").show();
	actual.map(function(_,i) {
		if (actual[i] != counts[i]) {
			$(":submit").attr("disabled", true);
			$(":submit").hide();
		}
	});
}

// Drag'n'drop functionality
function update_form (){
	var selects = $("select");
	var answers = $(".answer-panel");
	answers.each(function (i,a){
		var icon = $(a).find(".answer-icon");
		if (icon.length) {
			$(selects.get(i)).val(icon.data('answer'));
		} else {
			$(selects.get(i)).val('');
		}
	});
	update_submit();
}

// General helper to animate a few things
function smoothly (things, callback) {
	things.each(function (i,e) {
		$(e).data('pos_now', $(e).offset())
	});

	callback();

	// animate all motion
	things.each(function (n,e) {
		var e_pos_now = $(e).data('pos_now');
		var e_pos_target = $(e).offset();

		$(e).css('position', 'relative');
		$(e).css('top', e_pos_now.top - e_pos_target.top);
		$(e).css('left', e_pos_now.left - e_pos_target.left);
		$(e).animate({left: 0, top: 0});
	});
}

$(function (){
	$(".answer-icon").draggable({
		revert: true,
		zIndex: 100 ,
	});
	$(".answer-panel").droppable({
		accept: '.answer-icon',
		hoverClass: "panel-success",
		drop: function( event, ui ) {
			var panel = this;
			smoothly($(".answer-icon"), function() {
				// move existing icons back to the store
				$(panel).find(".answer-icon").appendTo("#answer-icons");

				// move draggable here
				ui.draggable.css({position: "relative", top:"", left:""});
				$(panel).find(".answer-icon-holder").prepend(ui.draggable);

				// Show placeholders only where relevant
				$(".answer-placeholder").show();
				$(".answer-panel").has(".answer-icon").find(".answer-placeholder").hide();
			});
			// Finally: Update form
			update_form();
		},
	});
});

$(function (){
	update_form();
	$("select").on('change', update_submit);
});

{% endblock %}

{% block content %}
<div class="container">
 <h2>
  <small>Was mag denn ein/eine</small>
  {{ word.lemma }}
  <small>sein?</small>
 </h2>

 <form role="form" method="POST">
  {% csrf_token %}

  {% for k, v in counts.items %}
   <input type="hidden" class="result-count" name="count-{{k}}" value="{{v}}" />
  {% endfor %}

  {% for e in explanations %}
   <div class="form-group" style="display: none">
   <label for="guess{{forloop.counter0}}" class="col-sm-4 control-label">{{ e.text }}</label>
    <div class="col-sm-2">
     <select id="id_guess{{forloop.counter0}}" name="guess{{forloop.counter0}}">
      <option value=""></option>
      <option value="0">Richtig</option>
      <option value="1">Mensch</option>
      <option value="2">Computer</option>
     </select>
    </div>
   </div>
  {% endfor %}

 <div class="container-fluid">
  <div class="row">
   {% for e in explanations %}
    <div class="col-md-4 col-sm-6">
     <div class="panel panel-default answer-panel">
      <table><tr>
       <td class="answer-icon-holder">
	    <img class="answer-placeholder" src="{% static "empty.png" %}"/>
	   </td>
       <td>
        {{ e.text }}
	   </td>
      </tr></table>
     </div>
    </div>
   {% if forloop.counter|divisibleby:"3" %}
    <div class="clearfix visible-md"></div>
   {% endif %}
   {% if forloop.counter|divisibleby:"2" %}
    <div class="clearfix visible-sm"></div>
   {% endif %}
   {% endfor %}
   <div class="col-md-4 col-md-6 text-center">
    <div id="answer-icons">
     {% for answer, count in counts.items %}
      {% for i in count|countup %}
       <img class="answer-icon" src="{% static "icon-" %}{{answer}}.png" data-answer="{{answer}}" alt="Antwort {{answer}}"/>
      {% endfor %}
     {% endfor %}
    </div>
    <input  class="btn btn-default" type="submit" value="Fertig!"/>
   </div>
  </div>
 </div>

 </form>
</div>

{% endblock %}

nbip_server/nbip/templates/nbip/login.html
{% extends "nbip/base.html" %}

{% load bootstrap %}

{% block title %}Einloggen{% endblock %}

{% block content %}

{% if form.errors %}
 <div class="container">
  <div class="alert-danger">
   Der Benutzername und das Passwort passen nicht zueinander. Bitte versuche es nochmal.
  </div>
 </div>
{% endif %}

<div class="container">
 <form class="form-inline" method="post" action="{% url 'django.contrib.auth.views.login' %}">
 {% csrf_token %}
  <div class="form-group">
    <label class="sr-only" for="id_username">Benutzername</label>
    <input type="text" class="form-control" name="username" id="id_username" maxlength="254" placeholder="Benutzername"/>
  </div>
  <div class="form-group">
    <label class="sr-only" for="id_password">Passwort</label>
    <input type="password" class="form-control" name="password" id="id_password" placeholder="Passwort" />
  </div>
  <input type="hidden" name="next" value="{{ next }}" />
  <button type="submit" class="btn btn-default">Sign in</button>
  <a class="btn btn-default" href="{% url "password_reset" %}">Passwort vergessen?</a>
</form>


</div>

{% endblock %}

nbip_server/nbip/templates/nbip/new_bot.html
{% extends "nbip/base.html" %}

{% load bootstrap %}

{% block title %}Neuen Bot anlegen{% endblock %}

{% block content %}

<div class="container">
<form class="form-horizontal" role="form" method="POST">
 {% for hidden in form.hidden_fields %}
    {{ hidden }}
 {% endfor %}
 {% csrf_token %}

<div class="form-group">
  <span class="control-label col-sm-4 col-lg-4 ">
   Meinen neuen Bot nenne ich
  </span>
  <div class="col-sm-4 col-lg-4 ">
    <input class="form-control" id="id_name" name="name" type="text" placeholder="{{user}}’s bot"/>
  </div>
 <div class="col-sm-2 col-lg-2">
  <input  class="btn btn-default" type="submit" value="Submit" />
 </div>
</div>
</form>

</div>
{% endblock %}

nbip_server/nbip/templates/nbip/submit.html
{% extends "nbip/base.html" %}

{% load bootstrap %}

{% block title %}Neues Wort einreichen{% endblock %}

{% block content %}

<div class="container">
<form class="form-horizontal" role="form" method="POST">
{% csrf_token %}

    {{ form.non_field_errors }}

{% for hidden in form.hidden_fields %}
    {{ hidden }}
{% endfor %}

 <div class="row">
  <div class="form-group">
   <div class="form-inline col-sm-8 col-sm-offset-2 ">
    Ein/eine
    <input class="form-control" id="id_lemma" name="{{ form.lemma.html_name }}" type="text" placeholder="&lt;Substantiv&gt;"/>
    {{ form.lemma.errors }}
    ist ein/eine
    <input class="form-control" id="id_explanation" name="{{ form.correct_explanation.name }}" type="text" placeholder="&lt;Adjektiv&gt; &lt;Substantiv&gt;"/>
    {{ form.correct_explanation.errors }}
   </div>
  </div>
 </div>

 <div class="row">
  <div class="form-group">
   <div class="form-inline col-sm-8 col-sm-offset-2 ">
    und mehr dazu findet man (optional) auf
    <input class="form-control" id="id_reference"  name="{{ form.reference.html_name }}" type="text" placeholder="http://"/>
    {{ form.reference.errors }}
  </div>
  </div>
 </div>

 <div class="row">
  <div class="form-group">
   <div class="col-sm-8 col-sm-offset-2">
    <input class="btn btn-default" type="submit" value="Wort einreichen" />
   </div>
  </div>
 </div>

</form>
</div>

{% endblock %}